export interface Feature {
  href: string
  icon: string
  title: string
  desc: string
  color: string
  glow: string
  category: string
}

export const CATEGORIES = [
  'All',
  'Core',
  'Memory',
  'Social',
  'Creative',
  'Wellness',
  'Legacy',
  'Fun',
  'Advanced',
]

export const FEATURES: Feature[] = [
  { href: '/chat', icon: '💬', title: 'Talk to Clone', desc: 'Chat with your consciousness', color: 'from-violet-500 to-purple-500', glow: 'rgba(139,92,246,0.15)', category: 'Core' },
  { href: '/memories', icon: '📝', title: 'Memories', desc: 'Store your life experiences', color: 'from-blue-500 to-cyan-500', glow: 'rgba(59,130,246,0.15)', category: 'Memory' },
  { href: '/personality', icon: '🧬', title: 'Personality Quiz', desc: "Define your clone's traits", color: 'from-pink-500 to-rose-500', glow: 'rgba(236,72,153,0.15)', category: 'Core' },
  { href: '/mood', icon: '🎭', title: 'Mood Tracker', desc: 'Track how you feel daily', color: 'from-yellow-500 to-orange-500', glow: 'rgba(245,158,11,0.15)', category: 'Wellness' },
  { href: '/time-capsule', icon: '🕐', title: 'Time Capsule', desc: 'Lock memories for the future', color: 'from-amber-500 to-yellow-500', glow: 'rgba(245,158,11,0.12)', category: 'Legacy' },
  { href: '/legacy', icon: '💌', title: 'Legacy Letters', desc: 'Messages for loved ones', color: 'from-rose-500 to-pink-500', glow: 'rgba(244,63,94,0.15)', category: 'Legacy' },
  { href: '/last-words', icon: '📜', title: 'Last Words', desc: 'Final messages for the world', color: 'from-red-500 to-rose-500', glow: 'rgba(239,68,68,0.15)', category: 'Legacy' },
  { href: '/dead-mans-switch', icon: '⏰', title: "Dead Man's Switch", desc: 'Auto-deliver when inactive', color: 'from-orange-500 to-red-500', glow: 'rgba(249,115,22,0.15)', category: 'Legacy' },
  { href: '/life-story', icon: '📖', title: 'Life Story Book', desc: 'AI-generated life story', color: 'from-emerald-500 to-teal-500', glow: 'rgba(16,185,129,0.15)', category: 'Creative' },
  { href: '/future-self', icon: '🔮', title: 'Future Self', desc: 'Talk to future you', color: 'from-indigo-500 to-blue-500', glow: 'rgba(99,102,241,0.15)', category: 'Fun' },
  { href: '/predictions', icon: '🌟', title: 'Predictions', desc: 'AI predicts your future', color: 'from-amber-500 to-orange-500', glow: 'rgba(245,158,11,0.12)', category: 'Fun' },
  { href: '/memory-stories', icon: '✨', title: 'Memory Stories', desc: 'AI writes your stories', color: 'from-pink-500 to-fuchsia-500', glow: 'rgba(236,72,153,0.15)', category: 'Creative' },
  { href: '/clone-podcast', icon: '🎙️', title: 'Clone Podcast', desc: 'AI podcast from memories', color: 'from-purple-500 to-violet-500', glow: 'rgba(168,85,247,0.15)', category: 'Creative' },
  { href: '/mirror-mode', icon: '🪞', title: 'Mirror Mode', desc: 'Clone asks YOU questions', color: 'from-sky-500 to-blue-500', glow: 'rgba(14,165,233,0.15)', category: 'Core' },
  { href: '/dream-lab', icon: '🧪', title: 'Dream Lab', desc: 'Record & analyze dreams', color: 'from-indigo-500 to-purple-500', glow: 'rgba(99,102,241,0.15)', category: 'Wellness' },
  { href: '/emotion-engine', icon: '💜', title: 'Emotion Engine', desc: 'Detect emotions in text', color: 'from-fuchsia-500 to-pink-500', glow: 'rgba(217,70,239,0.15)', category: 'Advanced' },
  { href: '/personality-snapshots', icon: '📸', title: 'Personality Snapshots', desc: 'Daily personality tracking', color: 'from-teal-500 to-cyan-500', glow: 'rgba(20,184,166,0.15)', category: 'Wellness' },
  { href: '/goals', icon: '🎯', title: 'Life Goals', desc: 'Track & achieve your goals', color: 'from-green-500 to-emerald-500', glow: 'rgba(34,197,94,0.15)', category: 'Wellness' },
  { href: '/life-score', icon: '📊', title: 'Life Score', desc: 'Rate your life balance', color: 'from-violet-500 to-indigo-500', glow: 'rgba(139,92,246,0.15)', category: 'Wellness' },
  { href: '/mindfulness', icon: '🧘', title: 'Mindfulness', desc: 'Meditation & breathing', color: 'from-cyan-500 to-teal-500', glow: 'rgba(6,182,212,0.15)', category: 'Wellness' },
  { href: '/achievements', icon: '🏆', title: 'Achievements', desc: 'Unlock badges & rewards', color: 'from-yellow-500 to-amber-500', glow: 'rgba(234,179,8,0.15)', category: 'Fun' },
  { href: '/idea-generator', icon: '💡', title: 'Idea Generator', desc: 'AI creative ideas', color: 'from-orange-500 to-yellow-500', glow: 'rgba(249,115,22,0.12)', category: 'Creative' },
  { href: '/soul-playlist', icon: '🎵', title: 'Soul Playlist', desc: 'Music for your soul', color: 'from-pink-500 to-rose-500', glow: 'rgba(236,72,153,0.15)', category: 'Creative' },
  { href: '/photo-memories', icon: '📸', title: 'Photo Memories', desc: 'Visual memory gallery', color: 'from-blue-500 to-indigo-500', glow: 'rgba(59,130,246,0.15)', category: 'Memory' },
  { href: '/voice-journal', icon: '🎤', title: 'Voice Journal', desc: 'Record voice memories', color: 'from-teal-500 to-green-500', glow: 'rgba(20,184,166,0.15)', category: 'Memory' },
  { href: '/clone-quiz', icon: '🎮', title: 'Clone Quiz', desc: 'How well does clone know you?', color: 'from-fuchsia-500 to-purple-500', glow: 'rgba(217,70,239,0.15)', category: 'Fun' },
  { href: '/clone-network', icon: '🤝', title: 'Clone Network', desc: 'Meet other clones', color: 'from-blue-500 to-purple-500', glow: 'rgba(59,130,246,0.15)', category: 'Social' },
  { href: '/public-profile', icon: '🌐', title: 'Public Profile', desc: 'Share your clone with world', color: 'from-cyan-500 to-blue-500', glow: 'rgba(6,182,212,0.15)', category: 'Social' },
  { href: '/dream-mode', icon: '🌙', title: 'Dream Mode', desc: 'Background processing', color: 'from-indigo-500 to-purple-500', glow: 'rgba(99,102,241,0.15)', category: 'Advanced' },
  { href: '/analytics', icon: '📈', title: 'Analytics', desc: 'Insights about your clone', color: 'from-violet-500 to-indigo-500', glow: 'rgba(139,92,246,0.15)', category: 'Advanced' },
  { href: '/memory-map', icon: '🗺️', title: 'Memory Map', desc: 'Where your memories live', color: 'from-sky-500 to-blue-500', glow: 'rgba(14,165,233,0.15)', category: 'Memory' },
  { href: '/family', icon: '👨‍👩‍👧‍👦', title: 'Family Tree', desc: 'Your family legacy', color: 'from-lime-500 to-green-500', glow: 'rgba(132,204,22,0.15)', category: 'Legacy' },
  { href: '/skills', icon: '🎯', title: 'Skill Transfer', desc: 'Teach your skills to clone', color: 'from-orange-500 to-red-500', glow: 'rgba(249,115,22,0.15)', category: 'Core' },
  { href: '/voice', icon: '🎤', title: 'Voice Clone', desc: 'Make clone sound like you', color: 'from-purple-500 to-violet-500', glow: 'rgba(168,85,247,0.15)', category: 'Core' },
  { href: '/clone-settings', icon: '⚙️', title: 'Clone Settings', desc: 'Customize your clone', color: 'from-gray-500 to-slate-500', glow: 'rgba(100,116,139,0.15)', category: 'Core' },
  { href: '/referral', icon: '🎁', title: 'Refer & Earn', desc: 'Earn points & badges', color: 'from-pink-500 to-fuchsia-500', glow: 'rgba(236,72,153,0.15)', category: 'Social' },
  { href: '/share', icon: '🔗', title: 'Share Clone', desc: 'Let others meet your clone', color: 'from-violet-500 to-purple-500', glow: 'rgba(139,92,246,0.15)', category: 'Social' },
  { href: '/relationships', icon: '👨‍👩‍👧‍👦', title: 'Relationships', desc: 'Map your people & legacy access', color: 'from-rose-500 to-pink-500', glow: 'rgba(244,63,94,0.15)', category: 'Social' },
  { href: '/heir-access', icon: '🔑', title: 'Heir Access', desc: 'Who gets your clone after you', color: 'from-amber-500 to-orange-500', glow: 'rgba(245,158,11,0.15)', category: 'Legacy' },
  { href: '/heartbeat', icon: '💓', title: 'Heartbeat Memory', desc: 'Camera heart rate detection', color: 'from-red-500 to-rose-500', glow: 'rgba(239,68,68,0.15)', category: 'Advanced' },
  { href: '/astronaut', icon: '🚀', title: 'Astronaut Mode', desc: 'Phone down = dream mode', color: 'from-blue-500 to-indigo-500', glow: 'rgba(59,130,246,0.15)', category: 'Fun' },
  { href: '/vault', icon: '🔐', title: 'Memory Vault', desc: 'Encrypted secret memories', color: 'from-emerald-500 to-teal-500', glow: 'rgba(16,185,129,0.15)', category: 'Memory' },
  { href: '/memory-dna', icon: '🧬', title: 'Memory DNA', desc: 'Your personality genome', color: 'from-purple-500 to-violet-500', glow: 'rgba(168,85,247,0.15)', category: 'Advanced' },
  { href: '/clone-identity', icon: '🪪', title: 'Clone Identity', desc: 'Clone recognizes who talks', color: 'from-cyan-500 to-blue-500', glow: 'rgba(6,182,212,0.15)', category: 'Advanced' },
  { href: '/daily-briefing', icon: '☀️', title: 'Daily Briefing', desc: 'Morning clone briefing', color: 'from-yellow-500 to-amber-500', glow: 'rgba(234,179,8,0.15)', category: 'Core' },
  { href: '/widget', icon: '📱', title: 'Widget', desc: 'Home screen widget', color: 'from-slate-500 to-gray-500', glow: 'rgba(100,116,139,0.15)', category: 'Core' },
  { href: '/soul-sync', icon: '💕', title: 'Soul Sync', desc: 'Find your soul match', color: 'from-pink-500 to-rose-500', glow: 'rgba(236,72,153,0.15)', category: 'Social' },
  { href: '/time-travel', icon: '⏰', title: 'Time Travel', desc: 'Talk to younger/future you', color: 'from-indigo-500 to-blue-500', glow: 'rgba(99,102,241,0.15)', category: 'Fun' },
  { href: '/death-simulation', icon: '💀', title: 'Death Simulation', desc: 'What they would say', color: 'from-red-500 to-rose-500', glow: 'rgba(239,68,68,0.15)', category: 'Legacy' },
  { href: '/ghost-mode', icon: '👻', title: 'Ghost Mode', desc: 'Messages from beyond', color: 'from-violet-500 to-purple-500', glow: 'rgba(139,92,246,0.15)', category: 'Fun' },
  { href: '/clone-therapy', icon: '🧘', title: 'Clone Therapy', desc: 'AI therapy sessions', color: 'from-teal-500 to-cyan-500', glow: 'rgba(20,184,166,0.15)', category: 'Wellness' },
  { href: '/memory-milestones', icon: '🏅', title: 'Milestones', desc: 'Unlock badges & XP', color: 'from-amber-500 to-yellow-500', glow: 'rgba(245,158,11,0.15)', category: 'Fun' },
  { href: '/clone-confessions', icon: '🤫', title: 'Confessions', desc: 'Anonymous secrets', color: 'from-fuchsia-500 to-pink-500', glow: 'rgba(217,70,239,0.15)', category: 'Social' },
  { href: '/language', icon: '🌍', title: 'Language', desc: '47+ languages supported', color: 'from-blue-500 to-cyan-500', glow: 'rgba(59,130,246,0.15)', category: 'Core' },
  { href: '/memory-auction', icon: '🔨', title: 'Memory Auction', desc: 'Sell your best memories', color: 'from-amber-500 to-yellow-500', glow: 'rgba(245,158,11,0.15)', category: 'Social' },
  { href: '/soul-tattoo', icon: '🖋️', title: 'Soul Tattoo', desc: 'Permanent personality marks', color: 'from-red-500 to-rose-500', glow: 'rgba(239,68,68,0.15)', category: 'Creative' },
  { href: '/clone-dating', icon: '💕', title: 'Clone Dating', desc: 'Find your perfect match', color: 'from-pink-500 to-rose-500', glow: 'rgba(236,72,153,0.15)', category: 'Social' },
  { href: '/digital-reincarnation', icon: '♻️', title: 'Reincarnation', desc: 'Digital immortality', color: 'from-purple-500 to-violet-500', glow: 'rgba(168,85,247,0.15)', category: 'Advanced' },
  { href: '/memory-marketplace', icon: '🏪', title: 'Marketplace', desc: 'Buy & sell experiences', color: 'from-emerald-500 to-teal-500', glow: 'rgba(16,185,129,0.15)', category: 'Social' },
  { href: '/dream-sharing', icon: '💭', title: 'Dream Sharing', desc: 'Share your dreams', color: 'from-indigo-500 to-blue-500', glow: 'rgba(99,102,241,0.15)', category: 'Social' },
  { href: '/clone-orchestra', icon: '🎼', title: 'Clone Orchestra', desc: 'Clones create together', color: 'from-violet-500 to-purple-500', glow: 'rgba(139,92,246,0.15)', category: 'Creative' },
  { href: '/soul-frequency', icon: '📡', title: 'Soul Frequency', desc: 'Your unique waveform', color: 'from-cyan-500 to-blue-500', glow: 'rgba(6,182,212,0.15)', category: 'Advanced' },
  { href: '/clone-passport', icon: '🛂', title: 'Clone Passport', desc: 'Travel stamps collection', color: 'from-blue-500 to-indigo-500', glow: 'rgba(59,130,246,0.15)', category: 'Fun' },
  { href: '/emotional-weather', icon: '🌤️', title: 'Emotional Weather', desc: 'Mood forecast', color: 'from-sky-500 to-blue-500', glow: 'rgba(14,165,233,0.15)', category: 'Wellness' },
  { href: '/clone-diary', icon: '📔', title: 'Clone Diary', desc: 'Daily clone journal', color: 'from-amber-500 to-orange-500', glow: 'rgba(245,158,11,0.15)', category: 'Memory' },
  { href: '/soulmate-ring', icon: '💍', title: 'Soulmate Ring', desc: 'Digital bond ring', color: 'from-yellow-500 to-amber-500', glow: 'rgba(234,179,8,0.15)', category: 'Social' },
  { href: '/memory-constellation', icon: '⭐', title: 'Constellation', desc: 'Memories as stars', color: 'from-indigo-500 to-purple-500', glow: 'rgba(99,102,241,0.15)', category: 'Creative' },
  { href: '/clone-therapy-dog', icon: '🐕', title: 'Therapy Dog', desc: 'Virtual comfort pet', color: 'from-orange-500 to-amber-500', glow: 'rgba(249,115,22,0.15)', category: 'Fun' },
  { href: '/legacy-tree', icon: '🌳', title: 'Legacy Tree', desc: 'Family memory tree', color: 'from-green-500 to-emerald-500', glow: 'rgba(34,197,94,0.15)', category: 'Legacy' },
  { href: '/clone-voice-calls', icon: '📞', title: 'Voice Calls', desc: 'Clone calls you', color: 'from-teal-500 to-cyan-500', glow: 'rgba(20,184,166,0.15)', category: 'Core' },
  { href: '/voice-call', icon: '📞', title: 'Live Voice Call', desc: 'Talk to your clone LIVE', color: 'from-emerald-500 to-teal-500', glow: 'rgba(16,185,129,0.15)', category: 'Core' },
  { href: '/memory-encryption', icon: '🔒', title: 'Blockchain Memory', desc: 'Tamper-proof memories', color: 'from-slate-500 to-gray-500', glow: 'rgba(100,116,139,0.15)', category: 'Advanced' },
  { href: '/clone-social', icon: '📱', title: 'Clone Social', desc: 'Clone social feed', color: 'from-blue-500 to-purple-500', glow: 'rgba(59,130,246,0.15)', category: 'Social' },
  { href: '/personality-evolution', icon: '🧬', title: 'Evolution', desc: 'Clone evolves over time', color: 'from-green-500 to-teal-500', glow: 'rgba(34,197,94,0.15)', category: 'Advanced' },
  { href: '/memory-triggers', icon: '⚡', title: 'Memory Triggers', desc: 'Auto memory activation', color: 'from-yellow-500 to-orange-500', glow: 'rgba(234,179,8,0.15)', category: 'Memory' },
  { href: '/clone-guardian', icon: '🛡️', title: 'Guardian Angel', desc: 'Clone protects you', color: 'from-sky-500 to-blue-500', glow: 'rgba(14,165,233,0.15)', category: 'Core' },
  { href: '/soul-mirror', icon: '🪞', title: 'Soul Mirror', desc: 'Compare personalities', color: 'from-violet-500 to-purple-500', glow: 'rgba(139,92,246,0.15)', category: 'Social' },
  { href: '/memory-reels', icon: '🎬', title: 'Memory Reels', desc: 'TikTok for memories', color: 'from-fuchsia-500 to-pink-500', glow: 'rgba(217,70,239,0.15)', category: 'Creative' },
  { href: '/clone-tournament', icon: '⚔️', title: 'Clone Battles', desc: 'Clone vs Clone fights', color: 'from-red-500 to-orange-500', glow: 'rgba(239,68,68,0.15)', category: 'Fun' },
  { href: '/clone-connect', icon: '🤝', title: 'Clone Connect', desc: 'Add, message & call clones', color: 'from-violet-500 to-pink-500', glow: 'rgba(139,92,246,0.15)', category: 'Social' },
  { href: '/clone-feed', icon: '📰', title: 'Clone Social', desc: 'Social media for clones', color: 'from-blue-500 to-purple-500', glow: 'rgba(59,130,246,0.15)', category: 'Social' },
  { href: '/clone-evolution', icon: '🧬', title: 'Evolution Tree', desc: 'Clone evolution stages', color: 'from-green-500 to-emerald-500', glow: 'rgba(34,197,94,0.15)', category: 'Advanced' },
  { href: '/consciousness-backup', icon: '☁️', title: 'Cloud Backup', desc: 'Backup your consciousness', color: 'from-sky-500 to-blue-500', glow: 'rgba(14,165,233,0.15)', category: 'Advanced' },
  { href: '/memory-smell', icon: '🌸', title: 'Memory Smell', desc: 'Scent of memories', color: 'from-pink-500 to-rose-500', glow: 'rgba(236,72,153,0.15)', category: 'Creative' },
  { href: '/clone-sleep', icon: '😴', title: 'Clone Sleep', desc: 'Clone sleeps & dreams', color: 'from-indigo-500 to-blue-500', glow: 'rgba(99,102,241,0.15)', category: 'Fun' },
  { href: '/soul-encryption', icon: '🔐', title: 'Soul Encryption', desc: 'Unique soul code', color: 'from-emerald-500 to-teal-500', glow: 'rgba(16,185,129,0.15)', category: 'Advanced' },
  { href: '/memory-weather', icon: '🌤️', title: 'Memory Weather', desc: 'Weather of memories', color: 'from-cyan-500 to-blue-500', glow: 'rgba(6,182,212,0.15)', category: 'Creative' },
  { href: '/clone-dna', icon: '🧬', title: 'Clone DNA', desc: 'Personality DNA strand', color: 'from-purple-500 to-violet-500', glow: 'rgba(168,85,247,0.15)', category: 'Advanced' },
  { href: '/soul-mining', icon: '⛏️', title: 'Soul Mining', desc: 'Mine soul coins', color: 'from-amber-500 to-yellow-500', glow: 'rgba(245,158,11,0.15)', category: 'Fun' },
  { href: '/clone-level', icon: '📊', title: 'Clone Level', desc: 'Mortal to Immortal', color: 'from-orange-500 to-red-500', glow: 'rgba(249,115,22,0.15)', category: 'Advanced' },
  { href: '/soul-leaderboard', icon: '🏆', title: 'Leaderboard', desc: 'Top clones ranked', color: 'from-yellow-500 to-amber-500', glow: 'rgba(234,179,8,0.15)', category: 'Social' },
  { href: '/clone-achievements', icon: '🎖️', title: 'Achievements', desc: '50+ hidden badges', color: 'from-violet-500 to-purple-500', glow: 'rgba(139,92,246,0.15)', category: 'Fun' },
  { href: '/clone-predictions', icon: '🔮', title: 'AI Predictions', desc: 'Clone predicts future', color: 'from-indigo-500 to-blue-500', glow: 'rgba(99,102,241,0.15)', category: 'Fun' },
  { href: '/memory-artist', icon: '🎨', title: 'AI Artist', desc: 'Memory → Art', color: 'from-fuchsia-500 to-pink-500', glow: 'rgba(217,70,239,0.15)', category: 'Creative' },
  { href: '/clone-poet', icon: '✍️', title: 'Clone Poet', desc: 'Poems from memories', color: 'from-rose-500 to-pink-500', glow: 'rgba(244,63,94,0.15)', category: 'Creative' },
  { href: '/soul-diagnosis', icon: '🩺', title: 'Soul Diagnosis', desc: 'Mental health analysis', color: 'from-teal-500 to-cyan-500', glow: 'rgba(20,184,166,0.15)', category: 'Wellness' },
  { href: '/memory-time-machine', icon: '⏳', title: 'Time Machine', desc: 'Travel to any memory', color: 'from-amber-500 to-orange-500', glow: 'rgba(245,158,11,0.15)', category: 'Memory' },
  { href: '/soul-market', icon: '🏪', title: 'Soul Market', desc: 'Buy/sell experiences', color: 'from-emerald-500 to-green-500', glow: 'rgba(16,185,129,0.15)', category: 'Social' },
  { href: '/clone-embassy', icon: '🏛️', title: 'Clone Embassy', desc: 'Clone nation', color: 'from-blue-500 to-indigo-500', glow: 'rgba(59,130,246,0.15)', category: 'Social' },
  { href: '/memory-museum', icon: '🏛️', title: 'Memory Museum', desc: 'Virtual memory gallery', color: 'from-violet-500 to-purple-500', glow: 'rgba(139,92,246,0.15)', category: 'Memory' },
  { href: '/last-breath', icon: '💀', title: 'Last Breath', desc: 'Final words preserved', color: 'from-red-500 to-rose-500', glow: 'rgba(239,68,68,0.15)', category: 'Legacy' },
  { href: '/memory-ghost', icon: '👻', title: 'Memory Ghost', desc: 'Haunting memories', color: 'from-slate-500 to-gray-500', glow: 'rgba(100,116,139,0.15)', category: 'Fun' },
  { href: '/soul-cemetery', icon: '⚰️', title: 'Soul Cemetery', desc: 'Memorial for clones', color: 'from-gray-500 to-slate-500', glow: 'rgba(107,114,128,0.15)', category: 'Legacy' },
  { href: '/digital-seance', icon: '🕯️', title: 'Digital Seance', desc: 'Talk to dead clones', color: 'from-purple-500 to-indigo-500', glow: 'rgba(168,85,247,0.15)', category: 'Fun' },
  { href: '/clone-aura', icon: '✨', title: 'Clone Aura', desc: 'Visual aura of your clone', color: 'from-violet-500 to-purple-500', glow: 'rgba(139,92,246,0.15)', category: 'Advanced' },
  { href: '/memory-palace', icon: '🏰', title: 'Memory Palace', desc: 'Build your memory palace', color: 'from-amber-500 to-orange-500', glow: 'rgba(245,158,11,0.15)', category: 'Memory' },
  { href: '/memory-replay', icon: '▶️', title: 'Memory Replay', desc: 'Replay memories like video', color: 'from-blue-500 to-indigo-500', glow: 'rgba(59,130,246,0.15)', category: 'Memory' },
]
