import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Clone Poet',
  description: 'Discover poetic expressions and verses generated by your digital consciousness.',
  openGraph: {
    title: 'Clone Poet | Consciousness Clone',
    description: 'Discover poetic expressions and verses generated by your digital consciousness.',
    type: 'website',
  },
}

export default function ClonePoetLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}
