import type { MetadataRoute } from 'next'

const BASE_URL = 'https://consciousness-clone.vercel.app'

export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes = [
    '',
    '/achievements',
    '/analytics',
    '/astronaut',
    '/blog',
    '/call-user',
    '/chat',
    '/chat-user',
    '/clone-achievements',
    '/clone-aura',
    '/clone-confessions',
    '/clone-connect',
    '/clone-dating',
    '/clone-diary',
    '/clone-dna',
    '/clone-embassy',
    '/clone-evolution',
    '/clone-feed',
    '/clone-guardian',
    '/clone-identity',
    '/clone-level',
    '/clone-network',
    '/clone-orchestra',
    '/clone-passport',
    '/clone-podcast',
    '/clone-poet',
    '/clone-predictions',
    '/clone-quiz',
    '/clone-settings',
    '/clone-sleep',
    '/clone-social',
    '/clone-therapy',
    '/clone-therapy-dog',
    '/clone-tournament',
    '/clone-voice-calls',
    '/consciousness-backup',
    '/daily-briefing',
    '/dashboard',
    '/dead-mans-switch',
    '/death-detection',
    '/death-simulation',
    '/digital-reincarnation',
    '/digital-seance',
    '/dream-lab',
    '/dream-mode',
    '/dream-sharing',
    '/emotion-engine',
    '/emotional-weather',
    '/family',
    '/future-self',
    '/ghost-mode',
    '/goals',
    '/heartbeat',
    '/heir-access',
    '/idea-generator',
    '/language',
    '/last-breath',
    '/last-words',
    '/legacy',
    '/legacy-tree',
    '/life-score',
    '/life-story',
    '/login',
    '/memories',
    '/memory-artist',
    '/memory-auction',
    '/memory-constellation',
    '/memory-dna',
    '/memory-encryption',
    '/memory-ghost',
    '/memory-map',
    '/memory-marketplace',
    '/memory-milestones',
    '/memory-museum',
    '/memory-palace',
    '/memory-reels',
    '/memory-replay',
    '/memory-smell',
    '/memory-stories',
    '/memory-time-machine',
    '/memory-triggers',
    '/memory-weather',
    '/mindfulness',
    '/mirror-mode',
    '/mood',
    '/personality',
    '/personality-evolution',
    '/personality-snapshots',
    '/photo-memories',
    '/predictions',
    '/pricing',
    '/privacy',
    '/public-profile',
    '/referral',
    '/relationships',
    '/share',
    '/signup',
    '/skills',
    '/soul-cemetery',
    '/soul-diagnosis',
    '/soul-encryption',
    '/soul-frequency',
    '/soul-leaderboard',
    '/soul-market',
    '/soul-mining',
    '/soul-mirror',
    '/soul-playlist',
    '/soul-sync',
    '/soul-tattoo',
    '/soul-transfer',
    '/soulmate-ring',
    '/terms',
    '/time-capsule',
    '/time-travel',
    '/vault',
    '/video-user',
    '/voice',
    '/voice-call',
    '/voice-journal',
    '/voice-user',
    '/widget',
  ]

  const highPriority = new Set([
    '',
    '/pricing',
    '/features',
    '/about',
  ])

  const mediumPriority = new Set([
    '/dashboard',
    '/chat',
    '/clone-feed',
    '/clone-network',
    '/memories',
    '/personality',
    '/mood',
    '/goals',
    '/skills',
    '/family',
    '/relationships',
    '/login',
    '/signup',
    '/blog',
    '/public-profile',
    '/analytics',
  ])

  return staticRoutes.map((route) => {
    const priority = highPriority.has(route)
      ? 1.0
      : mediumPriority.has(route)
        ? 0.8
        : 0.5

    const changeFrequency = highPriority.has(route)
      ? 'weekly'
      : mediumPriority.has(route)
        ? 'weekly'
        : 'monthly'

    return {
      url: `${BASE_URL}${route}`,
      lastModified: new Date(),
      changeFrequency: changeFrequency as MetadataRoute.Sitemap[number]['changeFrequency'],
      priority,
    }
  })
}
